name: Test Variant

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write & execute & read 

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Build with Gradle Wrapper
      run: ./gradlew build & sleep 30 -x 

    - name: Run Test
      run: ./gradlew/test

    - name: Upload report
      run: touch ./report_test/test_report.html & cat test_report
